services:
  redis:
    image: redis:7-alpine
    container_name: scheduler-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    container_name: scheduler-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scheduler
    ports:
      - "5432:5432"
    volumes:
      - scheduler-postgres-data:/var/lib/postgresql/data

volumes:
  scheduler-postgres-data:
