services:
  redis:
    image: redis:7-alpine
    container_name: scheduler-redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:v2.49.1
    container_name: scheduler-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./dev-prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./dev-prometheus/rules.yml:/etc/prometheus/rules.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: scheduler-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./dev-alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:16-alpine
    container_name: scheduler-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scheduler
    ports:
      - "5432:5432"
    volumes:
      - scheduler-postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: scheduler-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - scheduler-minio-data:/data

  minio-init:
    image: minio/mc:latest
    container_name: scheduler-minio-init
    depends_on:
      - minio
    entrypoint: ["/bin/sh","-lc"]
    command: >
      "
      set -e;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb -p local/scheduler-logs || true;
      mc anonymous set download local/scheduler-logs || true;
      echo 'minio-init done';
      "

volumes:
  scheduler-postgres-data:
  scheduler-minio-data:
