apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: scheduler-worker-pdb
  namespace: scheduler
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: scheduler-worker
